#!/bin/sh

#   -------------------------------------------------------------
#   Dovecot and Postfix Reload
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/core/certificates/files/acmesh/acmesh-dovecot_postfixReload.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>


service dovecot reload
service postfix reload
acmesh-nginxCheck
