#!/bin/sh

#   -------------------------------------------------------------
#   Nasqueron PaaS :: Alkane :: Recipe for deployment
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/webserver-content/org/nasqueron/files/recipes/mail.nasqueron.org/update.sh
#   Action:         init
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

#   -------------------------------------------------------------
#   Snappymail
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

cd "$ALKANE_SITE_PATH/snappymail"

curl https://snappymail.eu/repository/latest.tar.gz | tar --exclude data/ -xzf -
