#!/bin/sh

#   -------------------------------------------------------------
#   Kernel check script
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/core/monitoring/files/checks/nrpe/os_family/FreeBSD/check-kernel.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e
set -u

PATH=/bin:/usr/bin:/sbin

which freebsd-version > /dev/null || exit 3

VERSION_INSTALLED=$(freebsd-version -k)
VERSION_RUNNING=$(freebsd-version -r)

if [ "$VERSION_INSTALLED" != "$VERSION_RUNNING" ]; then
    echo "Reboot is needed for kernel upgrade $VERSION_RUNNING to $VERSION_INSTALLED"
    exit 1
fi

exit 0
