#!/bin/sh

#   -------------------------------------------------------------
#   OS release check script
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/core/monitoring/files/checks/nrpe/os_family/FreeBSD/check-os-release.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e
set -u

if [ ! -f /var/run/os-release ]; then
    echo "Restart service os-release to generate missing os-release file."
    exit 2
fi

PATH=/bin:/usr/bin:/sbin
which freebsd-version > /dev/null || exit 3
VERSION_INSTALLED=$(freebsd-version -k)

. /var/run/os-release

if [ "$VERSION_INSTALLED" != "$VERSION" ]; then
    echo "/etc/os-release isn't up-to-date, restart os-release service"
    exit 1
fi

exit 0
