#!/bin/sh

#   -------------------------------------------------------------
#   List IP and reverse DNS
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Eglide
#   Created:        2017-01-10
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/shellserver/vhosts/files/vhosts.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

if [ -f /etc/vhosts ]; then
    cat /etc/vhosts
else
    echo "No vhosts data file found. Please create /etc/vhosts file."
fi
