#!/bin/sh

#   -------------------------------------------------------------
#   OpenSearch security initializer
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/opensearch/opensearch/files/security_initialize.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

OPENSEARCH_HOSTNAME=$1
ROOT=/opt/opensearch

# Wait a little bit to let OpenSearch start
sleep 5

bash $ROOT/plugins/opensearch-security/tools/securityadmin.sh \
    -cacert $ROOT/config/root-ca.pem \
    -cert $ROOT/config/admin.pem \
    -key $ROOT/config/admin.key \
    -f $ROOT/plugins/opensearch-security/securityconfig/internal_users.yml \
    -nhnv -icl \
    -h "$OPENSEARCH_HOSTNAME"

touch $ROOT/plugins/opensearch-security/securityconfig/.initialized
