repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        language: system

      - id: check-executables-have-shebangs
        language: system

      - id: check-json
        language: system

      - id: check-merge-conflict
        language: system

      - id: check-xml
        language: system

      - id: check-yaml
        language: system

      - id: end-of-file-fixer
        exclude: ^roles/core/motd/files/
        language: system

      - id: fix-byte-order-marker
        language: system

      - id: mixed-line-ending
        language: system
        args: ["--fix=lf"]

      - id: trailing-whitespace
        language: system
        exclude: patch$

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/warpnet/salt-lint
    rev: v0.9.2
    hooks:
      - id: salt-lint
        args: ["-x", "207,208"]
        files: ^(roles|hotfixes).*\.(sls)$

  - repo: https://devcentral.nasqueron.org/source/codestyle.git
    rev: v0.1.1
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
