#!/bin/sh

#   -------------------------------------------------------------
#   Monitoring :: checks :: mailserver :: mail aliases
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        BSD-2-Clause
#   Source file:    roles/mailserver/monitoring/files/check-mail-aliases.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

ALIASES="/etc/mail/aliases"
ALIASES_DB="/etc/mail/aliases.db"

if [ ! -f "$ALIASES" ]; then
    echo "CRITICAL: $ALIASES not found"
    exit 2
fi

if [ ! -f "$ALIASES_DB" ]; then
    echo "WARNING: $ALIASES_DB not found (run newaliases)"
    exit 1
fi

if [ "$ALIASES" -nt "$ALIASES_DB" ]; then
    echo "WARNING: aliases newer than aliases.db (run newaliases)"
    exit 1
fi

echo "OK: aliases.db is up to date"
exit 0
