#!/bin/sh

#   -------------------------------------------------------------
#   Install Rhyne-Wyse in a virtual environment
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        BSD-2-Clause
#   Source file:    roles/reports/rhyne-wyse/files/build.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

VENV=/opt/rhyne-wyse/venv
TOOLS_ROOT_DIR=/opt/nasqueron-reports/tools

#   -------------------------------------------------------------
#   Initialize virtual environment
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

python3 -m venv $VENV
. $VENV/bin/activate
pip install --upgrade pip

pip install setuptools build

#   -------------------------------------------------------------
#   Build and install components
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

build_package_for_tool() {
    cd "$TOOLS_ROOT_DIR/$1"
    python3 -m build

    latest_package=$(find dist -name '*.whl' | sort | tail -n1)
    if [ -z "$latest_package" ]; then
        echo "[$1] No build artifact found in dist/" >&2
        exit 1
    fi

    pip install "$latest_package"
}

build_package_for_tool secretsmith
build_package_for_tool nasqueron-reports
build_package_for_tool rhyne-wyse
