#!/bin/sh

#   -------------------------------------------------------------
#   Rhyne-Wyse
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/reports/rhyne-wyse/files/rhyne-wyse.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

LOG=/var/log/rhyne-wyse.log
WORKDIR=/var/run/rhyne-wyse

#   -------------------------------------------------------------
#   Task :: update Agora reports
#
#   Logging is configured at bot level to output to stderr
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

cd $WORKDIR

. /opt/rhyne-wyse/venv/bin/activate
update-agora-reports >> $LOG 2>&1
