#   -------------------------------------------------------------
#   Pywikibot
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Created:        2017-11-15
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/viperserv/wikidata-access-layer/files/user-config.py
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

mylang = 'wikidata'
family = 'wikidata'
usernames['wikidata']['wikidata'] = u'DæghrefnBot'

console_encoding = 'utf-8'
