#   -------------------------------------------------------------
#   Vault configuration - Policy to run DRP bootstrap script
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/vault/vault/files/vault_boostrap.hcl
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

#   -------------------------------------------------------------
#   Secrets engine management
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

path "sys/mounts/*" {
  capabilities = [ "create", "read", "update", "delete", "list" ]
}

path "sys/mounts" {
  capabilities = [ "read", "list" ]
}

#   -------------------------------------------------------------
#   PKI
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

path "pki*" {
  capabilities = [ "create", "read", "update", "delete", "list", "sudo" ]
}
