#!/bin/sh

#   -------------------------------------------------------------
#   Nasqueron PaaS :: Alkane :: Recipe for deployment
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/webserver-content/org/nasqueron/files/recipes/admin.mail.nasqueron.org/update.sh
#   Action:         update
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

cd "$ALKANE_SITE_PATH"

#   -------------------------------------------------------------
#   Update git
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$CURRENT_BRANCH" != "production" ]; then
   echo "Code isn't in the production branch." >&2
   exit 1
fi

git fetch --all
git diff-index --quiet HEAD && git pull --rebase

#   -------------------------------------------------------------
#   Update composer
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

composer update --prefer-dist --no-dev
