#!/bin/sh

#   -------------------------------------------------------------
#   Rust :: Cargo :: Update registry index
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/devserver/userland-software/files/rust/cargo-index-update.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

#   -------------------------------------------------------------
#   Parse arguments
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") <toolchain>" >&2
    exit 1
fi

TOOLCHAIN=$1

#   -------------------------------------------------------------
#   Ensure rustup is available
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

USER=$(id -un)
RUSTUP="/home/${USER}/.cargo/bin/rustup"

if [ ! -x "$RUSTUP" ]; then
    # No rustup, nothing to update
    exit 0
fi

#   -------------------------------------------------------------
#   Trigger Cargo registry index update
#
#   As there is no command implemented, we can simulate any
#   operation normally triggering an update.
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

TMP_DIR=$(mktemp -d "/tmp/cargo-index-${USER}-${TOOLCHAIN}-XXXXXX") || exit 1
cd "$TMP_DIR" || exit 1
"$RUSTUP" run "$TOOLCHAIN" cargo init >/dev/null 2>&1
"$RUSTUP" run "$TOOLCHAIN" cargo add serde >/dev/null 2>&1
cd / || exit 1
rm -rf "$TMP_DIR"
