#!/bin/sh

#   -------------------------------------------------------------
#   Eggdrop liveness checker
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/viperserv/eggdrop/files/ensure-eggdrops-are-live.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

while IFS=' ' read -r eggdrop; do
    # Skip blank lines and comment lines
    take_first_character="?"
    first_character=${eggdrop%"${eggdrop#${take_first_character}}"}
    if [ "$first_character" = "#" ]; then
        continue
    elif [ "$eggdrop" = "" ]; then
        continue
    fi

    service eggdrop status "$eggdrop" > /dev/null
    status=$?

    if [ $status -ne 0 ]; then
        service eggdrop restart "$eggdrop"
    fi
done < /usr/local/etc/eggdrops-live.conf
