#   -------------------------------------------------------------
#   Vault configuration
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/vault/vault/files/vault.hcl
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

listener "tcp" {
  address = "{{ ip }}:8200"
{% if certificates_available %}
  tls_cert_file: "/usr/local/etc/certificates/vault/fullchain.pem"
  tls_key_file: "/usr/local/etc/certificates/vault/private.key"
{% else %}
  tls_disable = 1
{% endif %}
}

storage "raft" {
  path = "/var/db/vault"
  node_id = "{{ id }}"
}

disable_mlock = true

cluster_addr = "http://{{ ip }}:8201"
api_addr = "http://{{ ip }}:8200"
ui = true
