#!/usr/bin/env bash

#   -------------------------------------------------------------
#   Phabricator — Arcanist Docker container wrapper
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Author:         Sébastien Santoro aka Dereckson
#   Project:        Nasqueron
#   Created:        2016-01-01
#   Description:    Wrapper to run Arcanist as a Docker container
#   License:        Trivial work, not eligible to copyright
#   Image:          nasqueron/arcanist
#   Source file:    roles/paas-docker/devel/files/arc.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

#   -------------------------------------------------------------
#   Parse arguments
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -t 0 ]; then
	# If a stdin entry is available
	# launch the container in the
	# interactive mode
	FLAGS=-it
fi

# Logs are default disabled
PRINT_LOG=0

if [ "$1" = "shell" ]; then
	# Launch commands
	# in the container bash shell
	shift
	COMMAND=bash
else
	# Launch arc
	mkdir -p ~/.arc
	COMMAND=arc

	if [ "$1" = "call-conduit" ]; then
		# Enable log printing
		PRINT_LOG=1
		# Set a random name for the container
		INSTANCE="arc-"$(openssl rand -hex 21)
		FLAGS="-i -a=stdin --name=$INSTANCE"
	fi
fi

if [ -d ~/.arc/ssh ]; then
	VOLUME_SSH="-v $HOME/.arc/ssh:/home/$USER/.ssh"
else
	VOLUME_SSH=""
fi

#   -------------------------------------------------------------
#   Build image
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

test -v $UID && UID=$(id -u)
test -v $GID && GID=$(id -g)
IMAGE=nasqueron/arcanist:$UID-$GID

build_image () {
	BUILD_DIR=$(mktemp -d -t arc-build-XXXXXXXXXX)
	pushd "$BUILD_DIR" > /dev/null || exit 1
	>&2 echo "🔨 Building user-specific image $IMAGE for $USER"
	echo "FROM nasqueron/arcanist" > Dockerfile
	echo "RUN groupadd -r $USER -g $GID && mkdir /home/$USER && useradd -u $UID -r -g $USER -d /home/$USER -s /bin/bash $USER && chown -R $USER:$USER /home/$USER" >> Dockerfile
	docker build -t "$IMAGE" .
	popd > /dev/null
	rm -rf "$BUILD_DIR"
}

test ! -z $(docker images -q "$IMAGE") || build_image

#   -------------------------------------------------------------
#   Run container
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ $PRINT_LOG -eq 0 ]; then
	docker run $FLAGS --rm --user $UID:$GID -v ~/.arc:/opt/config -v "$PWD:/opt/workspace" $VOLUME_SSH $IMAGE $COMMAND "$@"
else
	docker run $FLAGS --user $UID:$GID -v ~/.arc:/opt/config -v "$PWD:/opt/workspace" $VOLUME_SSH $IMAGE $COMMAND "$@" > /dev/null
	sleep 3
	docker logs "$INSTANCE"
	docker rm "$INSTANCE" >/dev/null
fi
