#   -------------------------------------------------------------
#   Vault configuration
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/shellserver/vault/files/vault.hcl
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>


listener "tcp" {
  address = "127.0.0.1:8200"

  tls_cert_file = "{{ certificates_dir }}/fullchain.pem"
  tls_key_file = "{{ certificates_dir }}/private.key"
}

storage "raft" {
  path = "/var/db/vault"
  node_id = "{{ id }}"
}

disable_mlock = true

cluster_addr = "http://127.0.0.1:8201"
api_addr = "http://127.0.0.1:8200"
ui = true
