#!/bin/sh

#   -------------------------------------------------------------
#   Clean alternative to who
#   Prints the usernames of connected users by alphabetical order
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Author:         Sébastien Santoro aka Dereckson
#   Created:        2015-12-30
#   Licence:        Trivial work, not eligible to copyright
#   Source file:    roles/shellserver/user-session/files/whom.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

who | awk '{print $1}' | sort | uniq
