#!/bin/sh

#   -------------------------------------------------------------
#   Initialize PEFS
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        BSD-2-Clause
#   Description:    Set password for Terraform / OpenTofu PEFS
#   Usage:          initialize-pefs ops/infra/complector/terraform/pefs /opt/terraform.enc /opt/terraform/encrypted
#   Source file:    roles/salt-primary/opentofu/files/initialize-pefs.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

#   -------------------------------------------------------------
#   Parse arguments
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ $# -lt 3 ]; then
    echo "Usage: $(basename "$0") <Vault key path> <encrypted filesystem> <mount point>" >&2
    exit 1
fi

VAULT_PATH=$1
PEFS_ENC=$2
PEFS_MOUNT=$3

#   -------------------------------------------------------------
#   Ensure user belongs to correct group
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if ! id -Gn | tr ' ' '\n' | grep -E '^(ops|deploy)$' >/dev/null 2>&1; then
    echo "error: user must be a member of the ops or deploy group" >&2
    exit 1
fi

#   -------------------------------------------------------------
#   Mount filesystem
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if ! sudo -u deploy pefs mount "$PEFS_ENC" "$PEFS_MOUNT"; then
    echo "Error: Failed to mount PEFS" >&2
    exit 2
fi

#   -------------------------------------------------------------
#   Ensure unmount PEFS on exit
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

unmount_pefs() {
    sudo -u deploy pefs unmount "$PEFS_MOUNT" 2>/dev/null || true
}

trap unmount_pefs EXIT

if [ -f "$PEFS_ENC/.pefs.db" ]; then
    echo "That directory has already been initialized."
    exit 4
fi

#   -------------------------------------------------------------
#   Add a new chain element
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

vault kv get -field=password "$VAULT_PATH" | sudo -u deploy pefs addchain -fZ -j - "$PEFS_ENC"
