#!/bin/sh

#   -------------------------------------------------------------
#   Wrapper to securely manage Terraform state on PEFS
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   Usage:          tf <mount|unmount|init|plan|apply|state|...> ...
#   License:        BSD-2-Clause
#   Source file:    roles/salt-primary/opentofu/files/tf.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

REPO_TF_BASE="/opt/salt/nasqueron-operations/terraform"

TF_ROOT_DIR="/opt/terraform"
PEFS_ENC="/opt/terraform.enc"
PEFS_MOUNT="$TF_ROOT_DIR/encrypted"

VAULT_PATH="ops/infra/complector/terraform/pefs"

#   -------------------------------------------------------------
#   Ensure user belongs to correct group
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if ! id -Gn | tr ' ' '\n' | grep -E '^(ops|deploy)$' >/dev/null 2>&1; then
    echo "error: user must be a member of the ops or deploy group" >&2
    exit 1
fi

#   -------------------------------------------------------------
#   Handle maintenance commands: mount / unmount
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ "$1" = "mount" ]; then
    if ! mount | grep -q "${PEFS_ENC} on ${PEFS_MOUNT} (pefs"; then
        if ! sudo -u deploy pefs mount "$PEFS_ENC" "$PEFS_MOUNT"; then
            echo "Error: Failed to mount PEFS" >&2
            exit 2
        fi
    else
        echo "PEFS is already mounted." >&2
    fi

    if ! sudo -u deploy pefs showkeys -t "$PEFS_MOUNT"; then
        if ! vault kv get -field=password "$VAULT_PATH" | sudo -u deploy pefs addkey -a aes256-xts -c -j - "$PEFS_MOUNT"; then
            echo "Error: Failed to add PEFS key using password from Vault at $VAULT_PATH"
            exit 1
        fi
    else
        echo "PEFS key is already loaded." >&2
    fi
    exit 0
fi

if [ "$1" = "unmount" ] || [ "$1" = "umount" ]; then
    if mount | grep -q "${PEFS_ENC} on ${PEFS_MOUNT} (pefs"; then
        sudo -u deploy pefs unmount "$PEFS_MOUNT" || true
    else
        echo "PEFS is not mounted." >&2
    fi
    exit 0
fi

#   -------------------------------------------------------------
#   Get working directory
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

CURRENT_DIR="$(pwd)"

case "$CURRENT_DIR" in
    "${REPO_TF_BASE}"/*)
        # Remove REPO_TF_BASE/ prefix to get the subdirectory name
        TF_CONFIG="${CURRENT_DIR#"$REPO_TF_BASE/"}"

        # Ensure it's a single top-level directory (no nested slashes like foo/bar)
        case "$TF_CONFIG" in
            */*)
                echo "Error: You must be in a top-level Terraform subdirectory of $REPO_TF_BASE" >&2
                echo "Current directory: $CURRENT_DIR" >&2
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Error: Must be run from a subdirectory of $REPO_TF_BASE" >&2
        echo "Current directory: $CURRENT_DIR" >&2
        exit 1
        ;;
esac

#   -------------------------------------------------------------
#   Terraform or OpenTofu?
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

STILL_REQUIRE_TERRAFORM="openbao ovh-ops-backups"

is_terraform_config() {
    for terraform_subdir in $STILL_REQUIRE_TERRAFORM; do
        [ "$1" = "$terraform_subdir" ] && return 0
    done
    return 1
}

if is_terraform_config "$TF_CONFIG"; then
    TF=terraform
else
    TF=tofu
fi

#   -------------------------------------------------------------
#   Ensure unmount PEFS on exit
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

MOUNTED_BY_US=0

unmount_pefs() {
    if [ "$MOUNTED_BY_US" -eq 1 ]; then
        # Attempt to unmount, suppress errors if already unmounted or busy
        sudo -u deploy pefs unmount "$PEFS_MOUNT" 2>/dev/null || true
    fi
}

# Trap EXIT covers normal completion, script errors (exit 1), and signals (SIGINT/SIGTERM)
trap unmount_pefs EXIT

#   -------------------------------------------------------------
#   Mount and decrypt PEFS
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if ! mount | grep -q "${PEFS_ENC} on ${PEFS_MOUNT} (pefs"; then
    if ! sudo -u deploy pefs mount "$PEFS_ENC" "$PEFS_MOUNT"; then
        echo "Error: Failed to mount PEFS" >&2
        exit 2
    fi
    MOUNTED_BY_US=1
fi

if ! sudo -u deploy pefs showkeys -t "$PEFS_MOUNT"; then
    if ! vault kv get -field=password "$VAULT_PATH" | sudo -u deploy pefs addkey -a aes256-xts -c -j - "$PEFS_MOUNT"; then
        echo "Error: Failed to add PEFS key using password from Vault at $VAULT_PATH"
        exit 1
    fi
fi

#   -------------------------------------------------------------
#   Ensure Terraform directories exist
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

TF_STATES_DIR="${PEFS_MOUNT}/tf-states/${TF_CONFIG}"
export TF_DATA_DIR="${TF_ROOT_DIR}/tf-data/${TF_CONFIG}"

# shellcheck disable=SC2174
mkdir -p -m 770 "$TF_STATES_DIR" "$TF_DATA_DIR"

#   -------------------------------------------------------------
#   Call Terraform/OpenTofu
#
#   Pass all arguments directly to terraform.
#   The script will exit with Terraform's exact exit code,
#   and the trap will unmount PEFS.
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

$TF "$@"
