#!/bin/sh

#   -------------------------------------------------------------
#   Add a new partition to a device mapper volume group
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/core/userland-software/files/new-partition.sh
#
#   Usage:
#       new-partition <device> <volume group>
#                     <logical volume name> [mounting point]
#
#       If the mounting point is omitted, disk is mounted
#       in /<logical volume name>
#
#   Example:
#       new-partition /dev/sdb1 centos_dwellers wharf /wharf
#
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

# Parses arguments

if [ $# -lt 3 ] || [ $# -gt 4 ]; then
    echo 'Usage: new-partition <device> <volume group>'
    echo '                     <logical volume name> [mounting point]'
    exit 1
fi

DEVICE=$1
VG=$2
LVNAME=$3

if [ $# -eq 4 ]; then
    MOUNTING_POINT=$4
else
    MOUNTING_POINT=/$LVNAME
fi

# Creates, formats, mounts partion

pvcreate "$DEVICE"
vgextend "$VG" "$DEVICE"
lvcreate -l 100%FREE -n "$LVNAME" "$VG"
mkfs -t xfs "/dev/$VG/$LVNAME"
echo "/dev/mapper/$VG-$LVNAME $MOUNTING_POINT xfs defaults 1 2" >> /etc/ftab
mount "$MOUNTING_POINT"
