#!/bin/sh

#   -------------------------------------------------------------
#   PaaS Docker
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   Created:        2015-12-29
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/paas-docker/systemd-unit/files/docker-paas-stop-containers.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

docker-paas-list-containers | tac | xargs docker stop
