#   -------------------------------------------------------------
#   Salt :: tests :: config for Salt primary server
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        BSD-2-Clause
#   -------------------------------------------------------------

all:

test: netbox rabbitmq vault

netbox:
	./netbox.py

rabbitmq:
	./rabbitmq.py

vault:
	./vault.py
