#!/bin/sh

#   -------------------------------------------------------------
#   Nasqueron :: PaaS Docker :: Jenkins container wrapper
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/paas-docker/wrappers/files/jenkins.sh
#   Usage:          jenkins <container name> <command> [args]
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

CONTAINER_IP=$(sudo docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$1")
shift

ssh -l "$USER" -p 50022 "$CONTAINER_IP" $*
