#!/bin/sh

#   -------------------------------------------------------------
#   Nasqueron PaaS :: Alkane :: Recipe for deployment
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/webserver-alkane/alkane/files/recipes/_lib/update-package.sh
#   Action:         update
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

set -e

cd "$ALKANE_SITE_PATH"

if [ -f "composer.json" ]; then
    if [ ! -d "$ALKANE_SITE_PATH/vendor" ]; then
        echo "$ALKANE_SITE_PATH/vendor directory doesn't exist." >&2
        exit 2
    fi

    composer update
fi

if [ -f "package.json" ]; then
    if [ ! -d "$ALKANE_SITE_PATH/node_modules" ]; then
        echo "$ALKANE_SITE_PATH/node_modules directory doesn't exist." >&2
        exit 2
    fi

    yarn install
fi
