#   -------------------------------------------------------------
#   Vault configuration
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/paas-docker/containers/files/vault/vault.hcl
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>


listener "tcp" {
  address = "0.0.0.0:8200"

  tls_cert_file = "/vault/config/certificates/fullchain.pem"
  tls_key_file = "/vault/config/certificates/private.key"
}

storage "raft" {
  path = "/vault/storage"
  node_id = "{{ id }}"
}

disable_mlock = true

ui = true
