#!/bin/sh

#   -------------------------------------------------------------
#   Vault AppRole creator
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/devserver/userland-software/files/create-vault-approle.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

VAULT_POLICY=$1

vault write "auth/approle/role/$VAULT_POLICY" token_policies="$VAULT_POLICY" \
    token_ttl=1h token_max_ttl=4h

vault read "auth/approle/role/$VAULT_POLICY/role-id"
vault write -force "auth/approle/role/$VAULT_POLICY/secret-id"
