#!/bin/sh
#   -------------------------------------------------------------
#   PaaS Docker
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    roles/paas-docker/salt/files/credential.sh
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <credential key>" 1>&2;
    exit 1
fi

sudo salt-call credentials.get_password "$1" --out=json | jq .local
