<?php

/*  -------------------------------------------------------------
    Snappymail configuration
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Project:        Nasqueron
    License:        Trivial work, not eligible to copyright
    Source file:    roles/webserver-content/org/nasqueron/files/snappymail/include.php
    -------------------------------------------------------------

    <auto-generated>
        This file is managed by our rOPS SaltStack repository.

        Changes to this file may cause incorrect behavior
        and will be lost if the state is redeployed.
    </auto-generated>
                                                               */

/*  -------------------------------------------------------------
    Helper methods
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  */

function define_app_data_path(string $path) : void {
    // Avoid to create folders in the parent directory
    // starting by path, e.g. snappymail snappymail_data_ snappymail.htaccess
    // snappymailindex.html    snappymailindex.php     snappymailINSTALLED
    // snappymailSALT.php
    if (!str_ends_with($path, "/")) {
        $path .= "/";
    }

    define("APP_DATA_FOLDER_PATH", $path);
}

/*  -------------------------------------------------------------
    Snappymail configuration
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  */

define("MULTIDOMAIN", 1);

define_app_data_path("{{ data_path }}");
