#   -------------------------------------------------------------
#   Terraform :: OpenBao :: Policies :: Rhyne-Wyse
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    terraform/openbao/policies/rhyne-wyse.hcl
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

path "apps/data/rhyne-wyse/agora" {
    capabilities = [ "read" ]
}

path "ops/data/secrets/dbserver/cluster-B/users/rhyne-wyse" {
    capabilities = [ "read" ]
}
