#   -------------------------------------------------------------
#   Vault configuration - Policy for router nodes
#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Project:        Nasqueron
#   License:        Trivial work, not eligible to copyright
#   Source file:    terraform/openbao/policies/router.hcl
#   -------------------------------------------------------------
#
#   <auto-generated>
#       This file is managed by our rOPS SaltStack repository.
#
#       Changes to this file may cause incorrect behavior
#       and will be lost if the state is redeployed.
#   </auto-generated>

path "apps/data/network/carp-hyper-001-switch" {
    capabilities = [ "read" ]
}
