INSTALL=install
PREFIX=/usr/local

install:
	${INSTALL} files/run-wolfphab.sh ${PREFIX}/bin/run-wolfphab
	${INSTALL} files/run-devcentral.sh ${PREFIX}/bin/run-devcentral
	${INSTALL} files/run-aphlict.sh ${PREFIX}/bin/run-aphlict
